"""add description and upgrated_at columns to orders

Revision ID: 52a37ae162e0
Revises: dd141ac287e6
Create Date: 2025-08-11 16:37:54.851020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52a37ae162e0'
down_revision: Union[str, Sequence[str], None] = 'dd141ac287e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('description', sa.TEXT(), nullable=False))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'description')
    # ### end Alembic commands ###
